<?php

return [
        [
                'restaurant_id' => 1,
                'dish_name' => 'Pizza Margherita',
                'ingredients' => 'Farina, mozzarella',
                'dish_price' => 8,
                'visible' => true,
                'dish_image' => 'https://media-assets.lacucinaitaliana.it/photos/6436c696f536a5ce0d9ef0ac/16:9/w_2560%2Cc_limit/pizza%2520margherita.jpg',
        ],
        [
                'restaurant_id' => 1,
                'dish_name' => 'Pizza Romana',
                'ingredients' => 'mozzarella, pomodoro, prosciutto cotto, basilico',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://connexia-rovagnati-us-prod.s3.amazonaws.com/wp-content/uploads/2020/11/09161042/08_pizza-prosciutto.jpg',
        ],
        [
                'restaurant_id' => 1,
                'dish_name' => 'Pizza Diavola',
                'ingredients' => 'mozzarella, pomodoro, salame, cipolla, olio al peperoncino',
                'dish_price' => 12,
                'visible' => true,
                'dish_image' => 'https://www.iffco.it/sites/default/files/styles/free_crop/public/img/recipe/gran-cucina-pizza-diavola.jpg?h=de92a0b7&itok=eC0EvTVI',
        ],
        [
                'restaurant_id' => 1,
                'dish_name' => 'Pizza Capricciosa',
                'ingredients' => 'mozzarella, pomodoro, prosciutto coto, carciofi, wurstel',
                'dish_price' => 13,
                'visible' => true,
                'dish_image' => 'https://www.italianstylecooking.net/wp-content/uploads/2022/01/Pizza-capricciosa.jpg',
        ],
        [
                'restaurant_id' => 1,
                'dish_name' => 'Pizza Bianca',
                'ingredients' => 'mozzarella',
                'dish_price' => 5,
                'visible' => true,
                'dish_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTISkKo2aN6f5isMVEBCKyQU-N5WLnVMC32KmI72k9R5A&s',
        ],
        [
                'restaurant_id' => 2,
                'dish_name' => 'Insalata Greca',
                'ingredients' => 'Pomodori, cetrioli, olive, feta, cipolla rossa, origano, olio d\'oliva, aceto di vino rosso',
                'dish_price' => 9,
                'visible' => true,
                'dish_image' => 'https://www.insalatone.it/wp-content/uploads/2019/04/insalata-greca.jpg',
        ],
        [
                'restaurant_id' => 2,
                'dish_name' => 'Risotto ai Funghi Porcini',
                'ingredients' => 'Riso, funghi porcini, cipolla, brodo vegetale, vino bianco, parmigiano',
                'dish_price' => 12,
                'visible' => true,
                'dish_image' => 'https://www.gustoblog.it/articoli/img/risotto-ai-funghi-porcini.jpg',
        ],
        [
                'restaurant_id' => 2,
                'dish_name' => 'Lasagne alle Verdure',
                'ingredients' => 'Lasagne, zucchine, melanzane, peperoni, pomodori, mozzarella, besciamella',
                'dish_price' => 11,
                'visible' => true,
                'dish_image' => 'https://www.galbani.it/sites/default/files/styles/square_1024/public/2018-04/24/lasagne-vegetariane.jpg?itok=fLmr7g4C',
        ],
        [
                'restaurant_id' => 2,
                'dish_name' => 'Hummus con Verdure Crudite',
                'ingredients' => 'Ceci, tahini, olio d\'oliva, limone, aglio, peperoncino, carote, sedano, peperoni',
                'dish_price' => 8,
                'visible' => true,
                'dish_image' => 'https://www.salepepe.it/wp-content/uploads/2019/09/Hummus-di-ceci.jpg',
        ],
        [
                'restaurant_id' => 2,
                'dish_name' => 'Couscous alle Verdure',
                'ingredients' => 'Couscous, zucchine, melanzane, peperoni, pomodori, cipolla, uvetta, mandorle',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://www.galbani.it/sites/default/files/styles/square_1024/public/2018-04/24/couscous-alle-verdure.jpg?itok=dE4nUa2e',
        ],
        [
                'restaurant_id' => 3,
                'dish_name' => 'Tacos al Pastor',
                'ingredients' => 'Tortilla di mais, carne di maiale marinata, ananas, cipolla, coriandolo',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://www.mexicanplease.com/wp-content/uploads/2016/05/Tacos-al-Pastor-11.jpg',
        ],
        [
                'restaurant_id' => 3,
                'dish_name' => 'Guacamole',
                'ingredients' => 'Avocado, cipolla, pomodoro, lime, coriandolo, peperoncino',
                'dish_price' => 8,
                'visible' => true,
                'dish_image' => 'https://www.simplyrecipes.com/thmb/UsXh3tQfF5lDFyGsa_GiX4K5e2Y=/3413x2560/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2021__06__Guacamole-LEAD-VERTICAL-12f0bcbb8b4a48fda868a99debf91aa5.jpg',
        ],
        [
                'restaurant_id' => 3,
                'dish_name' => 'Enchiladas',
                'ingredients' => 'Tortilla di mais, pollo, salsa di pomodoro, formaggio, panna acida',
                'dish_price' => 12,
                'visible' => true,
                'dish_image' => 'https://www.simplyrecipes.com/thmb/2zArDdtfrv7LPqDCb1M47dEqO88=/4000x3000/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2021__09__enchiladas-verdes-horiz-a-4ed0d362ae7e4d54a9f8c10a94ee24b8.jpg',
        ],
        [
                'restaurant_id' => 3,
                'dish_name' => 'Quesadillas',
                'ingredients' => 'Tortilla di farina, formaggio, pollo, peperoni, cipolla',
                'dish_price' => 9,
                'visible' => true,
                'dish_image' => 'https://www.simplyrecipes.com/thmb/GSKxTs5OcjllBQmM1TTRwL-2GrI=/2667x2000/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2010__09__quesadillas-horiz-a-1600-9e315533a7b24b5fa1fc7340d1803bfb.jpg',
        ],
        [
                'restaurant_id' => 3,
                'dish_name' => 'Chiles Rellenos',
                'ingredients' => 'Peperoni poblano, formaggio, carne macinata, salsa di pomodoro',
                'dish_price' => 13,
                'visible' => true,
                'dish_image' => 'https://www.isabeleats.com/wp-content/uploads/2018/09/Chiles-Rellenos-Recipe-8-500x500.jpg',
        ],
        [
                'restaurant_id' => 4,
                'dish_name' => 'Sashimi Misto',
                'ingredients' => 'Pesce crudo fresco (tonno, salmone, branzino, ecc.)',
                'dish_price' => 18,
                'visible' => true,
                'dish_image' => 'https://www.sushi.com/wp-content/uploads/2018/07/sashimi-misto.jpg',
        ],
        [
                'restaurant_id' => 4,
                'dish_name' => 'Nigiri Sushi',
                'ingredients' => 'Riso, pesce crudo (tonno, salmone, gambero, ecc.)',
                'dish_price' => 3,
                'visible' => true,
                'dish_image' => 'https://www.sushifaq.com/sushi-guide/wp-content/uploads/2019/01/nigiri-sushi.jpg',
        ],
        [
                'restaurant_id' => 4,
                'dish_name' => 'Maki Sushi',
                'ingredients' => 'Riso, alga nori, pesce o verdure (tonno, avocado, cetriolo, ecc.)',
                'dish_price' => 9,
                'visible' => true,
                'dish_image' => 'https://d3cizcpymoenau.cloudfront.net/images/42527/original/42527.jpg?1551369255',
        ],
        [
                'restaurant_id' => 4,
                'dish_name' => 'Tempura Maki',
                'ingredients' => 'Riso, alga nori, tempura (gamberi o verdure)',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://www.eatthis.com/wp-content/uploads/sites/4/2021/04/shutterstock_1371657390.jpg',
        ],
        [
                'restaurant_id' => 4,
                'dish_name' => 'Sushi California Roll',
                'ingredients' => 'Riso, alga nori, avocado, surimi (crab stick), cetriolo',
                'dish_price' => 11,
                'visible' => true,
                'dish_image' => 'https://www.thaifoodmadeeasy.com/wp-content/uploads/2016/07/california-roll-sushi.png',
        ],
        [
                'restaurant_id' => 5,
                'dish_name' => 'Risotto ai Funghi Porcini',
                'ingredients' => 'Riso Carnaroli, funghi porcini freschi, scalogno, brodo vegetale, burro, parmigiano reggiano',
                'dish_price' => 20,
                'visible' => true,
                'dish_image' => 'https://www.gustissimo.it/articoli/ricette/risotto-ai-funghi-porcini/immagini/risotto-ai-funghi-porcini.jpg',
        ],
        [
                'restaurant_id' => 5,
                'dish_name' => 'Tagliatelle al Tartufo',
                'ingredients' => 'Tagliatelle fresche, tartufo nero pregiato, panna fresca, burro, parmigiano reggiano',
                'dish_price' => 25,
                'visible' => true,
                'dish_image' => 'https://i0.wp.com/www.chefsempreinpiedi.it/wp-content/uploads/2021/08/Tagliatelle-al-tartufo.jpg?fit=700%2C466&ssl=1',
        ],
        [
                'restaurant_id' => 5,
                'dish_name' => 'Filetto di Manzo alla Griglia',
                'ingredients' => 'Filetto di manzo, sale, pepe, olio extravergine di oliva',
                'dish_price' => 30,
                'visible' => true,
                'dish_image' => 'https://www.anticosannio.it/wp-content/uploads/2020/07/filetto-di-manzo-1.jpg',
        ],
        [
                'restaurant_id' => 5,
                'dish_name' => 'Bruschetta con Pomodorini e Basilico',
                'ingredients' => 'Pane casereccio, pomodorini ciliegino, basilico fresco, aglio, olio extravergine di oliva',
                'dish_price' => 15,
                'visible' => true,
                'dish_image' => 'https://www.ilcuoredinapoli.net/wp-content/uploads/2020/07/Bruschetta-pomodorini-basilico.jpg',
        ],
        [
                'restaurant_id' => 5,
                'dish_name' => 'Insalata Caprese',
                'ingredients' => 'Pomodori maturi, mozzarella di bufala, basilico fresco, olio extravergine di oliva, sale',
                'dish_price' => 18,
                'visible' => true,
                'dish_image' => 'https://www.gustissimo.it/articoli/ricette/insalata-caprese/immagini/insalata-caprese.jpg',
            ],
        [
                'restaurant_id' => 6,
                'dish_name' => 'Pizza Margherita',
                'ingredients' => 'Farina, mozzarella',
                'dish_price' => 8,
                'visible' => true,
                'dish_image' => 'https://media-assets.lacucinaitaliana.it/photos/6436c696f536a5ce0d9ef0ac/16:9/w_2560%2Cc_limit/pizza%2520margherita.jpg',
        ],
        [
                'restaurant_id' => 6,
                'dish_name' => 'Pizza Romana',
                'ingredients' => 'mozzarella, pomodoro, prosciutto cotto, basilico',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://connexia-rovagnati-us-prod.s3.amazonaws.com/wp-content/uploads/2020/11/09161042/08_pizza-prosciutto.jpg',
        ],
        [
                'restaurant_id' => 6,
                'dish_name' => 'Pizza Diavola',
                'ingredients' => 'mozzarella, pomodoro, salame, cipolla, olio al peperoncino',
                'dish_price' => 12,
                'visible' => true,
                'dish_image' => 'https://www.iffco.it/sites/default/files/styles/free_crop/public/img/recipe/gran-cucina-pizza-diavola.jpg?h=de92a0b7&itok=eC0EvTVI',
        ],
        [
                'restaurant_id' => 6,
                'dish_name' => 'Pizza Capricciosa',
                'ingredients' => 'mozzarella, pomodoro, prosciutto coto, carciofi, wurstel',
                'dish_price' => 13,
                'visible' => true,
                'dish_image' => 'https://www.italianstylecooking.net/wp-content/uploads/2022/01/Pizza-capricciosa.jpg',
        ],
        [
                'restaurant_id' => 6,
                'dish_name' => 'Pizza Bianca',
                'ingredients' => 'mozzarella',
                'dish_price' => 5,
                'visible' => true,
                'dish_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTISkKo2aN6f5isMVEBCKyQU-N5WLnVMC32KmI72k9R5A&s',
        ],

        [
                'restaurant_id' => 7,
                'dish_name' => 'Pollo alla Kung Pao',
                'ingredients' => 'Pollo, arachidi, peperoncino, peperoni, salsa di soia, zenzero, aglio',
                'dish_price' => 12,
                'visible' => true,
                'dish_image' => 'https://www.cucchiaio.it/content/cucchiaio/it/ricette/2017/06/pollo-kung-pao/jcr:content/header-par/image-single.img10.jpg/1498753174825.jpg',
        ],
        [
                'restaurant_id' => 7,
                'dish_name' => 'Manzo con Broccoli',
                'ingredients' => 'Manzo, broccoli, salsa di soia, aglio, olio di sesamo, zenzero',
                'dish_price' => 15,
                'visible' => true,
                'dish_image' => 'https://www.thespruceeats.com/thmb/Ed2MyO6-9JLbH9t-dTxgTiqcA9E=/450x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/beef-and-broccoli-recipe-694202-hero-02-93b44613e009498f9c7afca029a14e4d.jpg',
        ],
        [
                'restaurant_id' => 7,
                'dish_name' => 'Ravioli al Vapore (Jiaozi)',
                'ingredients' => 'Pasta di grano, ripieno di carne o verdure, salsa di soia',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://i.ytimg.com/vi/JBAYVqxZdyQ/maxresdefault.jpg',
        ],
        [
                'restaurant_id' => 7,
                'dish_name' => 'Anatra alla Pechinese',
                'ingredients' => 'Anatra, salsa hoisin, cipolla verde, cetrioli, pancake',
                'dish_price' => 20,
                'visible' => true,
                'dish_image' => 'https://www.cucchiaio.it/content/cucchiaio/it/ricette/2017/09/pezzi-di-anatra-al-forno-cinese/jcr:content/header-par/image-single.img10.jpg/1505709437751.jpg',
        ],
        [
                'restaurant_id' => 7,
                'dish_name' => 'Gamberi Fritti al Sale e Pepe',
                'ingredients' => 'Gamberi, sale, pepe, farina di mais, aglio, peperoncino',
                'dish_price' => 18,
                'visible' => true,
                'dish_image' => 'https://www.thespruceeats.com/thmb/Y4RdMl2JQoqR0Vs0Ew51tMkZ5Dc=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/salt-and-pepper-shrimp-recipe-694139-10_preview-5b04e8f2c9e77c00261e6409.jpeg',
        ],
        [
                'restaurant_id' => 8,
                'dish_name' => 'Kebab di Pollo',
                'ingredients' => 'Pollo marinato, insalata, pomodoro, cipolla, salse',
                'dish_price' => 7,
                'visible' => true,
                'dish_image' => 'https://www.simplyrecipes.com/thmb/Yl9NvXlTOwmt2fOvq9rWru9DGQc=/1500x844/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2011__10__chicken-kebabs-vertical-4-82cfc1250ec84cfda4b1b8e9f8e9f555.jpg',
        ],
        [
                'restaurant_id' => 8,
                'dish_name' => 'Kebab di Agnello',
                'ingredients' => 'Agnello marinato, insalata, pomodoro, cipolla, salse',
                'dish_price' => 8,
                'visible' => true,
                'dish_image' => 'https://www.simplyrecipes.com/thmb/lKuxMEH7FfwQzDXPLnM-1Eskm1A=/1920x1080/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2006__06__grilled-lamb-kebabs-vertical-a-1800-5e6e07c21f5e4b808217d30776a1276f.jpg',
        ],
        [
                'restaurant_id' => 8,
                'dish_name' => 'Falafel',
                'ingredients' => 'Ceci, prezzemolo, aglio, spezie, insalata, pomodoro, cipolla, salse',
                'dish_price' => 6,
                'visible' => true,
                'dish_image' => 'https://www.simplyrecipes.com/thmb/62rtmBjWMBG9q8Jy5Jn-NMRa1Ls=/2000x2000/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__05__Homemade-Falafel-LEAD-VERTICAL-0f86da7a3fc147248be1ec3c422a4a00.jpg',
        ],
        [
                'restaurant_id' => 8,
                'dish_name' => 'Shawarma',
                'ingredients' => 'Carne di manzo o pollo marinata, insalata, pomodoro, cipolla, salse',
                'dish_price' => 9,
                'visible' => true,
                'dish_image' => 'https://www.simplyrecipes.com/thmb/xxuQxH5i3qg9r3cvNw2LOfIEln4=/2000x1333/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2010__03__chicken-shawarma-horiz-a-1800-1544cf74d16a4378b98bfb5cfb399a3e.jpg',
        ],
        [
                'restaurant_id' => 8,
                'dish_name' => 'Kebab Vegetariano',
                'ingredients' => 'Falafel, insalata, pomodoro, cipolla, salse',
                'dish_price' => 7,
                'visible' => true,
                'dish_image' => 'https://www.simplyrecipes.com/thmb/62rtmBjWMBG9q8Jy5Jn-NMRa1Ls=/2000x2000/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2019__05__Homemade-Falafel-LEAD-VERTICAL-0f86da7a3fc147248be1ec3c422a4a00.jpg',
        ],
        [
                'restaurant_id' => 9,
                'dish_name' => 'Bibimbap',
                'ingredients' => 'Riso, verdure miste, carne marinata, uovo, gochujang (salsa piccante coreana)',
                'dish_price' => 15,
                'visible' => true,
                'dish_image' => 'https://www.thespruceeats.com/thmb/Nd1pWzxyf5lM1SueM9eSopE1RU4=/3000x2002/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Korean-bibimbap-975394802-56a8c9f25f9b58b7d0f4f654.jpg',
        ],
        [
                'restaurant_id' => 9,
                'dish_name' => 'Kimchi',
                'ingredients' => 'Cavolo cinese fermentato, peperoncino rosso in polvere, aglio, zenzero, pesce essiccato (opzionale)',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://www.thespruceeats.com/thmb/B_uSlFfFb28F0CJb0BygLVHg-X4=/2000x1333/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/kimchi-5867e11b3df78c17b6ac8607.jpg',
        ],
        [
                'restaurant_id' => 9,
                'dish_name' => 'Bulgogi',
                'ingredients' => 'Fettine di manzo marinato, salsa di soia, zucchero, aglio, sesamo',
                'dish_price' => 18,
                'visible' => true,
                'dish_image' => 'https://www.thespruceeats.com/thmb/uZuSjENfH2o6qwWxEJoJv3J4zGw=/3000x2002/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/bulgogi-korean-marinated-beef-recipe-2118795-hero-02-2dbbd8a3cbf74b2ca7af6a01903f6b26.jpg',
        ],
        [
                'restaurant_id' => 9,
                'dish_name' => 'Dak Galbi',
                'ingredients' => 'Pollo, salsa piccante, verdure miste, tteok (gnocchi di riso)',
                'dish_price' => 20,
                'visible' => true,
                'dish_image' => 'https://www.thespruceeats.com/thmb/nfHbmfiM06V8t1ME7tkV62MCTnk=/4000x2667/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/dak-galbi-korean-spicy-chicken-stir-fry-2118733-hero-01-f52b3315e8a94bb99017d9c56f56a1d1.jpg',
        ],
        [
                'restaurant_id' => 9,
                'dish_name' => 'Japchae',
                'ingredients' => 'Verdure miste, frittura di patate dolci, funghi, manzo marinato, glassa di soia',
                'dish_price' => 17,
                'visible' => true,
                'dish_image' => 'https://www.thespruceeats.com/thmb/cYXxvUznt2j7ueFRzBSnBpRXGuc=/3000x2000/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/korean-japchae-noodles-2118685-hero-01-775f5092ff204af2a5dd1b8e28e12ed2.jpg',
        ],
        [
                'restaurant_id' => 10,
                'dish_name' => 'Hamburger Classico',
                'ingredients' => 'Manzo macinato, pane per hamburger, lattuga, pomodoro, formaggio, ketchup, maionese',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://www.simplyrecipes.com/thmb/Ye0OrCXsXmFnI2rgJU4vTyVLtdk=/1200x800/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2022__07__Classic-Hamburger-LEAD-5-eef52b9b1d6e4d4e93507716ebd04c8f.jpg',
        ],
        [
                'restaurant_id' => 10,
                'dish_name' => 'Cheeseburger Bacon',
                'ingredients' => 'Manzo macinato, pane per hamburger, formaggio cheddar, bacon, lattuga, pomodoro, ketchup, maionese',
                'dish_price' => 12,
                'visible' => true,
                'dish_image' => 'https://www.simplyrecipes.com/thmb/2AJys0itVyUmqbEYD0EqPVv2G-0=/1200x800/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2021__08__bacon-cheeseburger-horiz-a-84d091a1136e432c8de39eebb6f0e26b.jpg',
        ],
        [
                'restaurant_id' => 10,
                'dish_name' => 'Panino Club',
                'ingredients' => 'Petto di pollo grigliato, bacon, pane tostato, lattuga, pomodoro, maionese',
                'dish_price' => 11,
                'visible' => true,
                'dish_image' => 'https://www.simplyrecipes.com/thmb/LH61Y9gH31zBmjHnpJnNys9zodY=/1920x1280/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2018__07__Club-Sandwich-LEAD-HORIZONTAL-cb5de51ff6db4f3cb9f1b114250bb7db.jpg',
        ],
        [
                'restaurant_id' => 10,
                'dish_name' => 'Panino Vegetariano',
                'ingredients' => 'Hummus, avocado, lattuga, pomodoro, cetrioli, pane integrale',
                'dish_price' => 9,
                'visible' => true,
                'dish_image' => 'https://www.simplyrecipes.com/thmb/1G6dKtU36-S4iR3HbGKZCxMW1hs=/1200x800/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2020__01__hummus-sandwich-vertical-a-1400-6be3d1fe0c3748d4a07aa1e465b2fb94.jpg',
        ],
        [
                'restaurant_id' => 10,
                'dish_name' => 'Hamburger Veggie',
                'ingredients' => 'Patty di verdure, pane per hamburger integrale, lattuga, pomodoro, formaggio, ketchup, maionese',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://www.simplyrecipes.com/thmb/TFYsZqfHNgOvqvlGcZgtFXrHSlI=/1200x800/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2013__07__veggie-burger-vertical-3-af5d6d1189ec4cb2a077971bf8356d22.jpg',
        ],
        [
                'restaurant_id' => 11,
                'dish_name' => 'Pizza Margherita',
                'ingredients' => 'Farina, mozzarella',
                'dish_price' => 8,
                'visible' => true,
                'dish_image' => 'https://media-assets.lacucinaitaliana.it/photos/6436c696f536a5ce0d9ef0ac/16:9/w_2560%2Cc_limit/pizza%2520margherita.jpg',
        ],
        [
                'restaurant_id' => 11,
                'dish_name' => 'Pizza Romana',
                'ingredients' => 'mozzarella, pomodoro, prosciutto cotto, basilico',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://connexia-rovagnati-us-prod.s3.amazonaws.com/wp-content/uploads/2020/11/09161042/08_pizza-prosciutto.jpg',
        ],
        [
                'restaurant_id' => 11,
                'dish_name' => 'Pizza Diavola',
                'ingredients' => 'mozzarella, pomodoro, salame, cipolla, olio al peperoncino',
                'dish_price' => 12,
                'visible' => true,
                'dish_image' => 'https://www.iffco.it/sites/default/files/styles/free_crop/public/img/recipe/gran-cucina-pizza-diavola.jpg?h=de92a0b7&itok=eC0EvTVI',
        ],
        [
                'restaurant_id' => 11,
                'dish_name' => 'Pizza Capricciosa',
                'ingredients' => 'mozzarella, pomodoro, prosciutto coto, carciofi, wurstel',
                'dish_price' => 13,
                'visible' => true,
                'dish_image' => 'https://www.italianstylecooking.net/wp-content/uploads/2022/01/Pizza-capricciosa.jpg',
        ],
        [
                'restaurant_id' => 11,
                'dish_name' => 'Pizza Bianca',
                'ingredients' => 'mozzarella',
                'dish_price' => 5,
                'visible' => true,
                'dish_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTISkKo2aN6f5isMVEBCKyQU-N5WLnVMC32KmI72k9R5A&s',
        ],
        [
                'restaurant_id' => 12,
                'dish_name' => 'Sashimi Misto',
                'ingredients' => 'Pesce crudo fresco (tonno, salmone, branzino, ecc.)',
                'dish_price' => 18,
                'visible' => true,
                'dish_image' => 'https://www.sushi.com/wp-content/uploads/2018/07/sashimi-misto.jpg',
        ],
        [
                'restaurant_id' => 12,
                'dish_name' => 'Nigiri Sushi',
                'ingredients' => 'Riso, pesce crudo (tonno, salmone, gambero, ecc.)',
                'dish_price' => 3,
                'visible' => true,
                'dish_image' => 'https://www.sushifaq.com/sushi-guide/wp-content/uploads/2019/01/nigiri-sushi.jpg',
        ],
        [
                'restaurant_id' => 12,
                'dish_name' => 'Maki Sushi',
                'ingredients' => 'Riso, alga nori, pesce o verdure (tonno, avocado, cetriolo, ecc.)',
                'dish_price' => 9,
                'visible' => true,
                'dish_image' => 'https://d3cizcpymoenau.cloudfront.net/images/42527/original/42527.jpg?1551369255',
        ],
        [
                'restaurant_id' => 12,
                'dish_name' => 'Tempura Maki',
                'ingredients' => 'Riso, alga nori, tempura (gamberi o verdure)',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://www.eatthis.com/wp-content/uploads/sites/4/2021/04/shutterstock_1371657390.jpg',
        ],
        [
                'restaurant_id' => 12,
                'dish_name' => 'Sushi California Roll',
                'ingredients' => 'Riso, alga nori, avocado, surimi (crab stick), cetriolo',
                'dish_price' => 11,
                'visible' => true,
                'dish_image' => 'https://www.thaifoodmadeeasy.com/wp-content/uploads/2016/07/california-roll-sushi.png',
        ],
];
