<?php

return [
        [
                'restaurant_id' => 1,
                'dish_name' => 'Pizza Margherita',
                'ingredients' => 'Farina, mozzarella',
                'dish_price' => 8,
                'visible' => 0,
                'dish_image' => 'https://media-assets.lacucinaitaliana.it/photos/6436c696f536a5ce0d9ef0ac/16:9/w_2560%2Cc_limit/pizza%2520margherita.jpg',
        ],
        [
                'restaurant_id' => 1,
                'dish_name' => 'Pizza Romana',
                'ingredients' => 'mozzarella, pomodoro, prosciutto cotto, basilico',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://connexia-rovagnati-us-prod.s3.amazonaws.com/wp-content/uploads/2020/11/09161042/08_pizza-prosciutto.jpg',
        ],
        [
                'restaurant_id' => 1,
                'dish_name' => 'Pizza Diavola',
                'ingredients' => 'mozzarella, pomodoro, salame, cipolla, olio al peperoncino',
                'dish_price' => 12,
                'visible' => 0,
                'dish_image' => 'https://www.iffco.it/sites/default/files/styles/free_crop/public/img/recipe/gran-cucina-pizza-diavola.jpg?h=de92a0b7&itok=eC0EvTVI',
        ],
        [
                'restaurant_id' => 1,
                'dish_name' => 'Pizza Capricciosa',
                'ingredients' => 'mozzarella, pomodoro, prosciutto coto, carciofi, wurstel',
                'dish_price' => 13,
                'visible' => 0,
                'dish_image' => 'https://www.italianstylecooking.net/wp-content/uploads/2022/01/Pizza-capricciosa.jpg',
        ],
        [
                'restaurant_id' => 1,
                'dish_name' => 'Pizza Bianca',
                'ingredients' => 'mozzarella',
                'dish_price' => 5,
                'visible' => 0,
                'dish_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTISkKo2aN6f5isMVEBCKyQU-N5WLnVMC32KmI72k9R5A&s',
        ],
        [
                'restaurant_id' => 2,
                'dish_name' => 'Insalata Greca',
                'ingredients' => 'Pomodori, cetrioli, olive, feta, cipolla rossa, origano, olio d\'oliva, aceto di vino rosso',
                'dish_price' => 9,
                'visible' => 0,
                'dish_image' => 'https://www.conad.it/assets/images/ricette/viabagutta/logo-rosso/ricetta-insalata-greca.jpg?_u=8075721954908b6427a6acc6eded235ee772ca15',
        ],
        [
                'restaurant_id' => 2,
                'dish_name' => 'Risotto ai Funghi Porcini',
                'ingredients' => 'Riso, funghi porcini, cipolla, brodo vegetale, vino bianco, parmigiano',
                'dish_price' => 12,
                'visible' => true,
                'dish_image' => 'https://www.buttalapasta.it/wp-content/uploads/2023/08/Risotto-ai-funghi-porcini-25082023-buttalapasta.it_.jpg',
        ],
        [
                'restaurant_id' => 2,
                'dish_name' => 'Lasagne alle Verdure',
                'ingredients' => 'Lasagne, zucchine, melanzane, peperoni, pomodori, mozzarella, besciamella',
                'dish_price' => 11,
                'visible' => 0,
                'dish_image' => 'https://media.grandchef.net/ricette/lasagna-bianca-con-verdure/galleria/lasagna-bianca-con-verdure.jpg',
        ],
        [
                'restaurant_id' => 2,
                'dish_name' => 'Hummus con Verdure Crudite',
                'ingredients' => 'Ceci, tahini, olio d\'oliva, limone, aglio, peperoncino, carote, sedano, peperoni',
                'dish_price' => 8,
                'visible' => 0,
                'dish_image' => 'https://www.sequestoeunuovo.it/wp-content/uploads/2019/03/IMG_8547_1200-e1553459734892.jpg',
        ],
        [
                'restaurant_id' => 2,
                'dish_name' => 'Couscous alle Verdure',
                'ingredients' => 'Couscous, zucchine, melanzane, peperoni, pomodori, cipolla, uvetta, mandorle',
                'dish_price' => 10,
                'visible' => 0,
                'dish_image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2021/10/couscous-finale-4-1200x675.jpg',
        ],
        [
                'restaurant_id' => 3,
                'dish_name' => 'Tacos al Pastor',
                'ingredients' => 'Tortilla di mais, carne di maiale marinata, ananas, cipolla, coriandolo',
                'dish_price' => 10,
                'visible' => 0,
                'dish_image' => 'https://www.culinaryhill.com/wp-content/uploads/2022/12/Tacos-al-Pastor-Culinary-Hill-1200x800-1.jpg',
        ],
        [
                'restaurant_id' => 3,
                'dish_name' => 'Guacamole',
                'ingredients' => 'Avocado, cipolla, pomodoro, lime, coriandolo, peperoncino',
                'dish_price' => 8,
                'visible' => 0,
                'dish_image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2021/12/guacamole-still-life-2-1200x675.jpg',
        ],
        [
                'restaurant_id' => 3,
                'dish_name' => 'Enchiladas',
                'ingredients' => 'Tortilla di mais, pollo, salsa di pomodoro, formaggio, panna acida',
                'dish_price' => 12,
                'visible' => 0,
                'dish_image' => 'https://www.allrecipes.com/thmb/bPzvJb8j15hg834N69dxmT74pik=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/26589-Beef-Enchiladas-with-Flour-Tortillas-ddmfs-202-4x3-a7e8ebda2d6a4a9c9b030e40395c5a2b.jpg',
        ],
        [
                'restaurant_id' => 3,
                'dish_name' => 'Quesadillas',
                'ingredients' => 'Tortilla di farina, formaggio, pollo, peperoni, cipolla',
                'dish_price' => 9,
                'visible' => true,
                'dish_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQE0ZwC1c9mwQ-JYpNxnj3OJ4cMZp-Cj4cvXywn5XHb9w&s',
        ],
        [
                'restaurant_id' => 3,
                'dish_name' => 'Chiles Rellenos',
                'ingredients' => 'Peperoni poblano, formaggio, carne macinata, salsa di pomodoro',
                'dish_price' => 13,
                'visible' => 0,
                'dish_image' => 'https://healthysimpleyum.com/wp-content/uploads/2021/06/IMG_5570-scaled-e1637283136659-883x1024.jpg',
        ],
        [
                'restaurant_id' => 4,
                'dish_name' => 'Sashimi Misto',
                'ingredients' => 'Pesce crudo fresco (tonno, salmone, branzino, ecc.)',
                'dish_price' => 18,
                'visible' => 0,
                'dish_image' => 'https://www.stuzzisushi.it/wp-content/uploads/2016/11/16-Sushi-Sashimi-misto-piccolo.jpg',
        ],
        [
                'restaurant_id' => 4,
                'dish_name' => 'Nigiri Sushi',
                'ingredients' => 'Riso, pesce crudo (tonno, salmone, gambero, ecc.)',
                'dish_price' => 3,
                'visible' => 0,
                'dish_image' => 'https://www.informacibo.it/wp-content/uploads/2023/06/NIGIRI-DI-SALMONE-ricetta.jpeg',
        ],
        [
                'restaurant_id' => 4,
                'dish_name' => 'Maki Sushi',
                'ingredients' => 'Riso, alga nori, pesce o verdure (tonno, avocado, cetriolo, ecc.)',
                'dish_price' => 9,
                'visible' => 0,
                'dish_image' => 'https://cdn.media.amplience.net/i/japancentre/guide-page-sushi-79-maki-sushi/Maki-sushi-rolls?$poi$&w=1200&h=630&sm=c&fmt=auto',
        ],
        [
                'restaurant_id' => 4,
                'dish_name' => 'Tempura Maki',
                'ingredients' => 'Riso, alga nori, tempura (gamberi o verdure)',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfn7zTPjC62oo3kskt3fkTP6u2ioszCeWrwtg-BwhwOA&s',
        ],
        [
                'restaurant_id' => 4,
                'dish_name' => 'Sushi California Roll',
                'ingredients' => 'Riso, alga nori, avocado, surimi (crab stick), cetriolo',
                'dish_price' => 11,
                'visible' => 0,
                'dish_image' => 'https://twodollareats.com/wp-content/uploads/2019/10/Two-Dollar-Eats-5265.jpg',
        ],
        [
                'restaurant_id' => 5,
                'dish_name' => 'Risotto ai Funghi Porcini',
                'ingredients' => 'Riso Carnaroli, funghi porcini freschi, scalogno, brodo vegetale, burro, parmigiano reggiano',
                'dish_price' => 20,
                'visible' => true,
                'dish_image' => 'https://www.buttalapasta.it/wp-content/uploads/2023/08/Risotto-ai-funghi-porcini-25082023-buttalapasta.it_.jpg',
        ],
        [
                'restaurant_id' => 5,
                'dish_name' => 'Tagliatelle al Tartufo',
                'ingredients' => 'Tagliatelle fresche, tartufo nero pregiato, panna fresca, burro, parmigiano reggiano',
                'dish_price' => 25,
                'visible' => 0,
                'dish_image' => 'https://www.italianmenumaster.com/images/94.jpg',
        ],
        [
                'restaurant_id' => 5,
                'dish_name' => 'Filetto di Manzo alla Griglia',
                'ingredients' => 'Filetto di manzo, sale, pepe, olio extravergine di oliva',
                'dish_price' => 30,
                'visible' => 0,
                'dish_image' => 'https://www.giallozafferano.it/images/215-21550/Filetto-di-manzo-in-crosta_780x520_wm.jpg',
        ],
        [
                'restaurant_id' => 5,
                'dish_name' => 'Bruschetta con Pomodorini e Basilico',
                'ingredients' => 'Pane casereccio, pomodorini ciliegino, basilico fresco, aglio, olio extravergine di oliva',
                'dish_price' => 15,
                'visible' => 0,
                'dish_image' => 'https://www.pursuedtirol.com/media/image/30/76/c1/Bruschetta-mit-Tomate-Mozzarella.jpg',
        ],
        [
                'restaurant_id' => 5,
                'dish_name' => 'Insalata Caprese',
                'ingredients' => 'Pomodori maturi, mozzarella di bufala, basilico fresco, olio extravergine di oliva, sale',
                'dish_price' => 18,
                'visible' => 0,
                'dish_image' => 'https://www.conad.it/assets/images/ricette/viabagutta/logo-rosso/ricetta-insalata-greca.jpg?_u=8075721954908b6427a6acc6eded235ee772ca15',
            ],
        [
                'restaurant_id' => 6,
                'dish_name' => 'Pizza Margherita',
                'ingredients' => 'Farina, mozzarella',
                'dish_price' => 8,
                'visible' => 0,
                'dish_image' => 'https://media-assets.lacucinaitaliana.it/photos/6436c696f536a5ce0d9ef0ac/16:9/w_2560%2Cc_limit/pizza%2520margherita.jpg',
        ],
        [
                'restaurant_id' => 6,
                'dish_name' => 'Pizza Romana',
                'ingredients' => 'mozzarella, pomodoro, prosciutto cotto, basilico',
                'dish_price' => 10,
                'visible' => 0,
                'dish_image' => 'https://connexia-rovagnati-us-prod.s3.amazonaws.com/wp-content/uploads/2020/11/09161042/08_pizza-prosciutto.jpg',
        ],
        [
                'restaurant_id' => 6,
                'dish_name' => 'Pizza Diavola',
                'ingredients' => 'mozzarella, pomodoro, salame, cipolla, olio al peperoncino',
                'dish_price' => 12,
                'visible' => 0,
                'dish_image' => 'https://www.iffco.it/sites/default/files/styles/free_crop/public/img/recipe/gran-cucina-pizza-diavola.jpg?h=de92a0b7&itok=eC0EvTVI',
        ],
        [
                'restaurant_id' => 6,
                'dish_name' => 'Pizza Capricciosa',
                'ingredients' => 'mozzarella, pomodoro, prosciutto coto, carciofi, wurstel',
                'dish_price' => 13,
                'visible' => 0,
                'dish_image' => 'https://www.italianstylecooking.net/wp-content/uploads/2022/01/Pizza-capricciosa.jpg',
        ],
        [
                'restaurant_id' => 6,
                'dish_name' => 'Pizza Bianca',
                'ingredients' => 'mozzarella',
                'dish_price' => 5,
                'visible' => true,
                'dish_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTISkKo2aN6f5isMVEBCKyQU-N5WLnVMC32KmI72k9R5A&s',
        ],

        [
                'restaurant_id' => 7,
                'dish_name' => 'Pollo alla Kung Pao',
                'ingredients' => 'Pollo, arachidi, peperoncino, peperoni, salsa di soia, zenzero, aglio',
                'dish_price' => 12,
                'visible' => 0,
                'dish_image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2021/04/Pollo-kung-pao-1200x675.jpg',
        ],
        [
                'restaurant_id' => 7,
                'dish_name' => 'Manzo con Broccoli',
                'ingredients' => 'Manzo, broccoli, salsa di soia, aglio, olio di sesamo, zenzero',
                'dish_price' => 15,
                'visible' => true,
                'dish_image' => 'https://www.ricetteslowcooker.it/wp-content/uploads/2017/04/manzo-e-broccoli_06-973x649.jpg',
        ],
        [
                'restaurant_id' => 7,
                'dish_name' => 'Ravioli al Vapore (Jiaozi)',
                'ingredients' => 'Pasta di grano, ripieno di carne o verdure, salsa di soia',
                'dish_price' => 10,
                'visible' => 0,
                'dish_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXLW4jmI1SnSXh3XzpP9bm40TZcR2WW55v09J6ea_ilw&s',
        ],
        [
                'restaurant_id' => 7,
                'dish_name' => 'Anatra alla Pechinese',
                'ingredients' => 'Anatra, salsa hoisin, cipolla verde, cetrioli, pancake',
                'dish_price' => 20,
                'visible' => 0,
                'dish_image' => 'https://www.gustissimo.it/articoli/ricette/pollame/anatra-alla-pechinese.jpg',
        ],
        [
                'restaurant_id' => 7,
                'dish_name' => 'Gamberi Fritti al Sale e Pepe',
                'ingredients' => 'Gamberi, sale, pepe, farina di mais, aglio, peperoncino',
                'dish_price' => 18,
                'visible' => 0,
                'dish_image' => 'https://www.ricettasprint.it/wp-content/uploads/2021/06/Gamberi-al-pepe-nella-friggitrice-ad-aria.jpg',
        ],
        [
                'restaurant_id' => 8,
                'dish_name' => 'Kebab di Pollo',
                'ingredients' => 'Pollo marinato, insalata, pomodoro, cipolla, salse',
                'dish_price' => 7,
                'visible' => 0,
                'dish_image' => 'https://www.antoniettapolcaro.it/wp-content/uploads/2023/08/piadina-kebab-pollo-antonietta-polcaro.jpg',
        ],
        [
                'restaurant_id' => 8,
                'dish_name' => 'Kebab di Agnello',
                'ingredients' => 'Agnello marinato, insalata, pomodoro, cipolla, salse',
                'dish_price' => 8,
                'visible' => 0,
                'dish_image' => 'https://libshop.fr/wp-content/uploads/2020/03/shawarma-lebanon.jpg',
        ],
        [
                'restaurant_id' => 8,
                'dish_name' => 'Falafel',
                'ingredients' => 'Ceci, prezzemolo, aglio, spezie, insalata, pomodoro, cipolla, salse',
                'dish_price' => 6,
                'visible' => 0,
                'dish_image' => 'https://www.cucchiaio.it/content/cucchiaio/it/ricette/2021/08/falafel/jcr:content/procedure-par/recipe_procedures_1529823373/image.img10.jpg/1629720909321.jpg',
        ],
        [
                'restaurant_id' => 8,
                'dish_name' => 'Shawarma',
                'ingredients' => 'Carne di manzo o pollo marinata, insalata, pomodoro, cipolla, salse',
                'dish_price' => 9,
                'visible' => true,
                'dish_image' => 'https://libshop.fr/wp-content/uploads/2020/03/shawarma-lebanon.jpg',
        ],
        [
                'restaurant_id' => 8,
                'dish_name' => 'Kebab Vegetariano',
                'ingredients' => 'Falafel, insalata, pomodoro, cipolla, salse',
                'dish_price' => 7,
                'visible' => 0,
                'dish_image' => 'https://www.antoniettapolcaro.it/wp-content/uploads/2023/08/piadina-kebab-pollo-antonietta-polcaro.jpg',
        ],
        [
                'restaurant_id' => 9,
                'dish_name' => 'Bibimbap',
                'ingredients' => 'Riso, verdure miste, carne marinata, uovo, gochujang (salsa piccante coreana)',
                'dish_price' => 15,
                'visible' => 0,
                'dish_image' => 'https://www.simplyquinoa.com/wp-content/uploads/2022/04/quinoa-bibimbap-3-500x500.jpg',
        ],
        [
                'restaurant_id' => 9,
                'dish_name' => 'Kimchi',
                'ingredients' => 'Cavolo cinese fermentato, peperoncino rosso in polvere, aglio, zenzero, pesce essiccato (opzionale)',
                'dish_price' => 10,
                'visible' => 0,
                'dish_image' => 'https://www.chilipeppermadness.com/wp-content/uploads/2021/12/Kimchi-SQ-500x500.jpg',
        ],
        [
                'restaurant_id' => 9,
                'dish_name' => 'Bulgogi',
                'ingredients' => 'Fettine di manzo marinato, salsa di soia, zucchero, aglio, sesamo',
                'dish_price' => 18,
                'visible' => 0,
                'dish_image' => 'https://images.immediate.co.uk/production/volatile/sites/2/2022/09/Bulgogi-a63fca6.jpg',
        ],
        [
                'restaurant_id' => 9,
                'dish_name' => 'Dak Galbi',
                'ingredients' => 'Pollo, salsa piccante, verdure miste, tteok (gnocchi di riso)',
                'dish_price' => 20,
                'visible' => 0,
                'dish_image' => 'https://theodehlicious.com/wp-content/uploads/2021/09/Cheese-Dakgalbi.jpg',
        ],
        [
                'restaurant_id' => 9,
                'dish_name' => 'Japchae',
                'ingredients' => 'Verdure miste, frittura di patate dolci, funghi, manzo marinato, glassa di soia',
                'dish_price' => 17,
                'visible' => true,
                'dish_image' => null,
        ],
        [
                'restaurant_id' => 10,
                'dish_name' => 'Hamburger Classico',
                'ingredients' => 'Manzo macinato, pane per hamburger, lattuga, pomodoro, formaggio, ketchup, maionese',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://www.lenaturelle.it/wp-content/uploads/2022/04/Hamburger-classico.jpg',
        ],
        [
                'restaurant_id' => 10,
                'dish_name' => 'Cheeseburger Bacon',
                'ingredients' => 'Manzo macinato, pane per hamburger, formaggio cheddar, bacon, lattuga, pomodoro, ketchup, maionese',
                'dish_price' => 12,
                'visible' => 0,
                'dish_image' => 'https://www.lenaturelle.it/wp-content/uploads/2022/04/Hamburger-classico.jpg',
        ],
        [
                'restaurant_id' => 10,
                'dish_name' => 'Panino Club',
                'ingredients' => 'Petto di pollo grigliato, bacon, pane tostato, lattuga, pomodoro, maionese',
                'dish_price' => 11,
                'visible' => 0,
                'dish_image' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2017/12/ricetta_club-sandwich-1280x720.jpg',
        ],
        [
                'restaurant_id' => 10,
                'dish_name' => 'Panino Vegetariano',
                'ingredients' => 'Hummus, avocado, lattuga, pomodoro, cetrioli, pane integrale',
                'dish_price' => 9,
                'visible' => 0,
                'dish_image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2019/03/hamburger-quinoa.jpg',
        ],
            [
                'restaurant_id' => 10,
                'dish_name' => 'Hamburger Veggie',
                'ingredients' => 'Patty di verdure, pane per hamburger integrale, lattuga, pomodoro, formaggio, ketchup, maionese',
                'dish_price' => 10,
                'visible' => 0,
                'dish_image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2019/03/hamburger-quinoa.jpg',
            ],
        [
                'restaurant_id' => 11,
                'dish_name' => 'Pizza Margherita',
                'ingredients' => 'Farina, mozzarella',
                'dish_price' => 8,
                'visible' => 0,
                'dish_image' => 'https://media-assets.lacucinaitaliana.it/photos/6436c696f536a5ce0d9ef0ac/16:9/w_2560%2Cc_limit/pizza%2520margherita.jpg',
        ],
        [
                'restaurant_id' => 11,
                'dish_name' => 'Pizza Romana',
                'ingredients' => 'mozzarella, pomodoro, prosciutto cotto, basilico',
                'dish_price' => 10,
                'visible' => true,
                'dish_image' => 'https://connexia-rovagnati-us-prod.s3.amazonaws.com/wp-content/uploads/2020/11/09161042/08_pizza-prosciutto.jpg',
        ],
        [
                'restaurant_id' => 11,
                'dish_name' => 'Pizza Diavola',
                'ingredients' => 'mozzarella, pomodoro, salame, cipolla, olio al peperoncino',
                'dish_price' => 12,
                'visible' => 0,
                'dish_image' => 'https://www.iffco.it/sites/default/files/styles/free_crop/public/img/recipe/gran-cucina-pizza-diavola.jpg?h=de92a0b7&itok=eC0EvTVI',
        ],
        [
                'restaurant_id' => 11,
                'dish_name' => 'Pizza Capricciosa',
                'ingredients' => 'mozzarella, pomodoro, prosciutto coto, carciofi, wurstel',
                'dish_price' => 13,
                'visible' => 0,
                'dish_image' => 'https://www.italianstylecooking.net/wp-content/uploads/2022/01/Pizza-capricciosa.jpg',
        ],
        [
                'restaurant_id' => 11,
                'dish_name' => 'Pizza Bianca',
                'ingredients' => 'mozzarella',
                'dish_price' => 5,
                'visible' => 0,
                'dish_image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTISkKo2aN6f5isMVEBCKyQU-N5WLnVMC32KmI72k9R5A&s',
        ],
        [
                'restaurant_id' => 12,
                'dish_name' => 'Sashimi Misto',
                'ingredients' => 'Pesce crudo fresco (tonno, salmone, branzino, ecc.)',
                'dish_price' => 18,
                'visible' => 0,
                'dish_image' => 'https://primochef.it/wp-content/uploads/2021/11/SH_sashimi_di_salmone.jpg.webp',
        ],
        [
                'restaurant_id' => 12,
                'dish_name' => 'Nigiri Sushi',
                'ingredients' => 'Riso, pesce crudo (tonno, salmone, gambero, ecc.)',
                'dish_price' => 3,
                'visible' => true,
                'dish_image' => 'https://alaskaseafood.it/wp-content/uploads/2021/11/nigiri-di-salmone-selvaggio-alaska.jpg',
        ],
        [
                'restaurant_id' => 12,
                'dish_name' => 'Maki Sushi',
                'ingredients' => 'Riso, alga nori, pesce o verdure (tonno, avocado, cetriolo, ecc.)',
                'dish_price' => 9,
                'visible' => 0,
                'dish_image' => 'https://alaskaseafood.it/wp-content/uploads/2021/11/nigiri-di-salmone-selvaggio-alaska.jpg',
        ],
        [
                'restaurant_id' => 12,
                'dish_name' => 'Tempura Maki',
                'ingredients' => 'Riso, alga nori, tempura (gamberi o verdure)',
                'dish_price' => 10,
                'visible' => 0,
                'dish_image' => 'https://www.ristoranteumi.it/wp-content/uploads/2020/08/Ristorante_UMI_359.jpg',
        ],
        [
                'restaurant_id' => 12,
                'dish_name' => 'Sushi California Roll',
                'ingredients' => 'Riso, alga nori, avocado, surimi (crab stick), cetriolo',
                'dish_price' => 11,
                'visible' => 0,
                'dish_image' => 'https://twodollareats.com/wp-content/uploads/2019/10/Two-Dollar-Eats-5265.jpg',
        ],


];
