<?php

return  [
    [
        'id' => 1,
        'user_id' => 1,
        'restaurant_name' => 'Pizzeria La Salsiera',
        'vat' => 'IT150908011',
        'address' => 'Via Roma, 184, Milano',
        'image' => 'https://images.deliveryhero.io/image/stores-glovo/stores/c7dadd68744eb18fb539de6d01a55d8b009328047fe579e6971119250f667ca5?t=W3siYXV0byI6eyJxIjoibG93In19LHsicmVzaXplIjp7ImhlaWdodCI6MjI1fX1d',
        'phone' => '+39 3457896756',
        'description' => "Il nostro motto è semplice: la pizza con l'ananas è tanta roba.",
    ], 
    [
        'id' => 2,
        'user_id' => 2,
        'restaurant_name' => 'Al Cantinone',
        'vat' => 'IT150908012',
        'address' => 'Via Agnello, 19, Milano',
        'image' => 'https://www.alcantinone.it/media/widgetkit/TTT2-ecc5912ebb509d049624ce36cb400dc9.jpg',
        'phone' => '+39 3457896656',
        'description' => "Trattoria storica nel centro di Milano. Dal 1930! Anche vegano e vegetariano...",
    ],
    [
        'id' => 3,
        'user_id' => 3,
        'restaurant_name' => 'Taqueria El Sol',
        'vat' => 'IT150508014',
        'address' => 'Via Solferino, 12, Milano',
        'image' => 'https://media-assets.lacucinaitaliana.it/photos/61fafc5bf623496b223ed316/4:3/w_2272,h_1704,c_limit/migliori-ristoranti-messicani-milano-tacos.jpg',
        'phone' => '+39 3457896856',
        'description' => 'Gustosi tacos, burritos e margarita in un ambiente festoso e colorato.',
    ],
    [
        'id' => 4,
        'user_id' => 4,
        'restaurant_name' => 'Sushi Zen',
        'vat' => 'IT150608015',
        'address' => 'Corso Garibaldi, 88, Milano',
        'image' => 'https://flawless.life/wp-content/uploads/2016/07/migliori-sushi-milano-fingers-garden.jpg',
        'phone' => '+39 3457896956',
        'description' => 'Autentico sushi giapponese preparato con pesce fresco e ingredienti di prima qualità.',
    ],
    [
        'id' => 5,
        'user_id' => 5,
        'restaurant_name' => 'Il Grottino',
        'vat' => 'IT150708016',
        'address' => 'Via Montenapoleone, 10, Milano',
        'image' => 'https://i0.wp.com/www.umbrianelmondo.com/wp-content/uploads/2022/07/Ristorante-interno-Il-Grottino-1-scaled.jpg?fit=2560%2C1707&ssl=1',
        'phone' => '+39 3457897056',
        'description' => 'Un angolo di Toscana nel cuore di Milano, con piatti tradizionali e vini pregiati.',
    ],
    [
        'id' => 6,
        'user_id' => 6,
        'restaurant_name' => 'Il Forno Rustico',
        'vat' => 'IT150808017',
        'address' => 'Via Manzoni, 45, Milano',
        'image' => 'https://ilrusticodeiconti.it/wp-content/uploads/2019/07/13-1.jpg',
        'phone' => '+39 3457897156',
        'description' => 'Pane e pizza sfornati giornalmente, con ricette tradizionali e ingredienti di alta qualità.',
    ],
    [
        'id' => 7,
        'user_id' => 7,
        'restaurant_name' => 'Lanterna Rossa',
        'vat' => 'IT150808018',
        'address' => 'Via Leopardi, 123, Milano',
        'image' => 'https://flawless.life/wp-content/uploads/2020/02/I_migliori_ristoranti_cinesi_Milano_BonWei.jpg',
        'phone' => '+39 3457897158',
        'description' => 'Ristorante Cinese doc in centro a Milano',
    ],
    [
        'id' => 8,
        'user_id' => 8,
        'restaurant_name' => 'Kebab da Mounir',
        'vat' => 'IT150808020',
        'address' => 'Via ciao ciao, 13, Milano',
        'image' => 'https://www.ilprimatonazionale.it/wp-content/uploads/2018/01/doner-kebab.jpg',
        'phone' => '+39 3456897158',
        'description' => 'Fast food a base di Kebab. Cosa volere di più?',
    ],
    [
        'id' => 9,
        'user_id' => 9,
        'restaurant_name' => 'Korean Dreams',
        'vat' => 'IT150808023',
        'address' => 'Via Korea, 35, Milano',
        'image' => 'https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/2022-04/Imone.jpg',
        'phone' => '+39 3456894158',
        'description' => 'Specialità coreane Milano',
    ],
    [
        'id' => 10,
        'user_id' => 10,
        'restaurant_name' => 'Hamburgeria',
        'vat' => 'IT150808027',
        'address' => 'Via Sandonato, 89, Milano',
        'image' => 'https://scattidigusto.b-cdn.net/wp-content/uploads/2016/04/hamburger-Milano-Rock-Burger-640x361.jpg',
        'phone' => '+39 3457894158',
        'description' => 'Hamburger che vanno in buca!',
    ],
    [
        'id' => 11,
        'user_id' => 11,
        'restaurant_name' => 'Le DOP',
        'vat' => 'IT150808030',
        'address' => 'Via Tamburello, 9, Milano',
        'image' => 'https://www.fradiavolopizzeria.com/articoliImg/art-16-gallery-1_1664354530.jpg',
        'phone' => '+39 3337894158',
        'description' => 'Pizza gourmet',
    ],
    [
        'id' => 12,
        'user_id' => 12,
        'restaurant_name' => 'Sushi Station',
        'vat' => 'IT150808032',
        'address' => 'Via Pochino, 92, Milano',
        'image' => 'https://www.ristoranteneko.it/new20/wp-content/uploads/2021/03/uramaki-1-1080x675.jpg',
        'phone' => '+39 3337494158',
        'description' => 'All you can eat. Sushi a volontà!',
    ],
];
